$:.unshift File.dirname(__FILE__)

require 'rubygems'
require 'nicovideo/mechanize-ext'
require 'nicovideo/base'
require 'nicovideo/page'
require 'nicovideo/videopage'
require 'nicovideo/comments'
require 'nicovideo/mylist'
require 'nicovideo/openlist'
require 'nicovideo/search'
require 'nicovideo/tagsearch'
require 'nicovideo/ranking'
require 'nicovideo/random'
require 'nicovideo/newarrival'
require 'nicovideo/thumbnail'
#require 'nicovideo/tags'
#require 'nicovideo/ichiba'
#require 'nicovideo/feed'

require 'nicovideo/community/community_page'
require 'nicovideo/community/main'
